version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: literalura
      MYSQL_USER: jose
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
