spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/literalura
    username: jose
    password: 1234
  jpa:
    properties:
      hibernate:
        ddl-auto: update

